# Generated by Django 4.2.13 on 2024-08-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_published',
            field=models.BooleanField(blank=True, choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, null=True, verbose_name='Статус'),
        ),
    ]
