# Generated by Django 4.2.13 on 2024-08-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_game_dislikes_remove_game_likes_uservote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservote',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], null=True),
        ),
    ]
