# Generated by Django 4.2.13 on 2024-08-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_uservote_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='saled_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
